# Generated by Django 5.2 on 2025-04-23 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='basliq')),
                ('message', models.TextField(verbose_name='mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxunub')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='gonderilme tarixi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='musteri')),
            ],
            options={
                'verbose_name': 'bildiris',
                'verbose_name_plural': 'bildirisler',
            },
        ),
    ]
