# Generated by Django 5.1 on 2025-05-01 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_codes', to='notifications.notification', verbose_name='bildiris')),
                ('user', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_codes', to=settings.AUTH_USER_MODEL, verbose_name='admin')),
            ],
            options={
                'verbose_name': 'admin kodu',
                'verbose_name_plural': 'admin kodlari',
            },
        ),
        migrations.CreateModel(
            name='BonusPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('last_notified_points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_points', to=settings.AUTH_USER_MODEL, verbose_name='musteri')),
            ],
            options={
                'verbose_name': 'bonus xal',
                'verbose_name_plural': 'bonus xallar',
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_codes', to='notifications.notification', verbose_name='bildiris')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to=settings.AUTH_USER_MODEL, verbose_name='bildiris')),
            ],
            options={
                'verbose_name': 'endirim kodu',
                'verbose_name_plural': 'endirim kodlari',
            },
        ),
    ]
