# Generated by Django 5.2 on 2025-04-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Nagd'), ('card', 'Kart')], default='cash', max_length=10, verbose_name='Odenis novu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'gozleyir'), ('completed', 'tamamlandi'), ('cancelled', 'legv olundu')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
